name: Deploy to Prod Site
run-name: Deploying to Prod Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo ${{secrets.USER_PASSWORD}} | sudo -S pm2 stop all
          cd /var/www/bradleycaravana.com
          echo ${{secrets.USER_PASSWORD}} | sudo -S git pull
          echo ${{secrets.USER_PASSWORD}} | sudo -S npm install
          echo ${{secrets.USER_PASSWORD}} | sudo -S npm run build
          echo ${{secrets.USER_PASSWORD}} | sudo -S pm2 restart all
