name: Deploy to Dev Site
run-name: Deploying to Dev Site
on:
  push:
    branches:
      - "dev"
jobs:
  deploy-to-dev:
    runs-on: self-hosted

    steps:
      - name: Build and Deploy
        run: |
          sudo pm2 stop all
          cd /var/www/dev.bradleycaravana.com
          sudo git pull
          sudo rm -rf node_modules
          sudo npm install
          sudo npm run build
          sudo pm2 restart all
