name: Deploy to Dev Site
run-name: Deploying to Dev Site
on:
  push:
    branches:
      - "dev"
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        run: |
          ssh -tt bradley@${{secrets.DROPLET_IP}}
          # sudo pm2 stop all
          # cd /var/www/dev.bradleycaravana.com
          # sudo git pull
          # sudo rm -rf node_modules
          # sudo npm install
          # sudo npm run build
          # sudo pm2 restart all
