# name: Deploy to Dev Site
# run-name: Deploying to Dev Site
# on:
#   push:
#     branches:
#       - "dev"
# jobs:
#   deploy-to-dev:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build and Deploy
#         run: |
#           ssh -tt bradley@24.199.90.153
name: Deploy to Dev Site
run-name: Deploying to Dev Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo ${{secrets.USER_PASSWORD}} | sudo -S pm2 stop all
          cd /var/www/dev.bradleycaravana.com
          echo ${{secrets.USER_PASSWORD}} | sudo -S git pull
          echo ${{secrets.USER_PASSWORD}} | sudo -S npm install
          echo ${{secrets.USER_PASSWORD}} | sudo -S npm run build
          echo ${{secrets.USER_PASSWORD}} | sudo -S pm2 restart all
