name: Deploy to Dev Site
run-name: Deploying to Dev Site
on:
  push:
    branches:
      - "dev"
jobs:
  deploy-to-dev:
    runs-on: self-hosted

    steps:
      - name: Build and Deploy
        run: |
          pm2 stop all
          cd /var/www/dev.bradleycaravana.com
          sudo git pull
          sudo npm install
          sudo npm run build
          pm2 restart all
